lab:
  Stereo:
      red:
        max:
        - 255
        - 255
        - 255
        min:
        - 70
        - 130
        - 130
      green:
        max:
        - 255
        - 127
        - 255
        min:
        - 50
        - 0
        - 0
      blue:
        max:
        - 255
        - 255
        - 127
        min:
        - 50
        - 0
        - 0
size:
  height: [480]
  width: [640]
